/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

import dao.JogadorDAO;
import javax.swing.JOptionPane;
import modelo.Jogador;
import java.util.List;

/**
 *
 * @author Lais Acosta
 */
public class Login extends javax.swing.JFrame {

    List<Jogador> lista;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        JogadorDAO dao = new JogadorDAO();
        lista = dao.listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLogin2 = new javax.swing.JTextField();
        txtSenha2 = new javax.swing.JTextField();
        botaook = new javax.swing.JButton();
        botaocadastrar2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Login:");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Senha:");

        txtLogin2.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N

        txtSenha2.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N

        botaook.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        botaook.setForeground(new java.awt.Color(0, 204, 0));
        botaook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        botaook.setText("Ok");
        botaook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaookActionPerformed(evt);
            }
        });

        botaocadastrar2.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        botaocadastrar2.setForeground(new java.awt.Color(0, 204, 0));
        botaocadastrar2.setText("Cadastrar");
        botaocadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocadastrar2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 2, 14)); // NOI18N
        jLabel3.setText("Ainda não é cadastrado?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogin2)
                            .addComponent(txtSenha2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(botaook)
                        .addGap(18, 18, 18)
                        .addComponent(botaocadastrar2)
                        .addGap(12, 12, 12)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaook)
                    .addComponent(botaocadastrar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaocadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocadastrar2ActionPerformed
        Cadastrar c = new Cadastrar();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaocadastrar2ActionPerformed

    private void botaookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaookActionPerformed
        Boolean deu;
        if (txtLogin2.getText().isEmpty() || txtSenha2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            deu = false;
        } else {
            deu = true;
        }
        if (deu == true) {
            for (Jogador jogador : lista) {
                if (txtLogin2.getText().equals(jogador.getLogin()) || txtSenha2.getText().equals(jogador.getSenha())) {
                    if (txtLogin2.getText().equals(jogador.getLogin()) && txtSenha2.getText().equals(jogador.getSenha())) {
                        PerguntaJogo p = new PerguntaJogo();
                        p.setVisible(true);
                        dispose();
                        JOptionPane.showMessageDialog(null, "Logado com sucesso.");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null, "Login e/ou senha incorretos.");
                        break;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Registro não encontrado.");
                    break;
                }
            }
        }
    }//GEN-LAST:event_botaookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaocadastrar2;
    private javax.swing.JButton botaook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtLogin2;
    private javax.swing.JTextField txtSenha2;
    // End of variables declaration//GEN-END:variables
}
