/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

import dao.PerguntaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Pergunta;

/**
 *
 * @author Lais Acosta
 */
public class PerguntaJogo extends javax.swing.JFrame {

    List<Pergunta> lista;
    Integer posicao;

    /**
     * Creates new form Pergunta
     */
    public PerguntaJogo() {
        initComponents();
        PerguntaDAO dao = new PerguntaDAO();
        lista = dao.listar();
        posicao = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JLabel();
        label1 = new javax.swing.JRadioButton();
        label2 = new javax.swing.JRadioButton();
        label3 = new javax.swing.JRadioButton();
        label4 = new javax.swing.JRadioButton();
        botaoconfirmar = new javax.swing.JButton();
        botaoparar = new javax.swing.JButton();
        botaocartas = new javax.swing.JButton();
        botaopular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lancarpergunta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PERGUNTA");

        txtEnunciado.setFont(new java.awt.Font("Lucida Fax", 2, 12)); // NOI18N
        txtEnunciado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label1.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N

        label2.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        label2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2ActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N

        label4.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        label4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label4ActionPerformed(evt);
            }
        });

        botaoconfirmar.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        botaoconfirmar.setForeground(new java.awt.Color(0, 204, 0));
        botaoconfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        botaoconfirmar.setText("Confirmar");
        botaoconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoconfirmarActionPerformed(evt);
            }
        });

        botaoparar.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        botaoparar.setForeground(new java.awt.Color(255, 0, 0));
        botaoparar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stop.png"))); // NOI18N
        botaoparar.setText("Parar");
        botaoparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopararActionPerformed(evt);
            }
        });

        botaocartas.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        botaocartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sequencia-de-Aces.jpg"))); // NOI18N
        botaocartas.setText("Cartas");
        botaocartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocartasActionPerformed(evt);
            }
        });

        botaopular.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        botaopular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/blue_right_arrow_99.jpg"))); // NOI18N
        botaopular.setText("Pular");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.png"))); // NOI18N

        lancarpergunta.setFont(new java.awt.Font("Lucida Fax", 2, 14)); // NOI18N
        lancarpergunta.setText("Lançar a pergunta!");
        lancarpergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancarperguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lancarpergunta)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoparar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoconfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaopular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaocartas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(label1))
                    .addComponent(lancarpergunta))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(label2)
                        .addGap(18, 18, 18)
                        .addComponent(label3)
                        .addGap(18, 18, 18)
                        .addComponent(label4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoconfirmar)
                    .addComponent(botaoparar)
                    .addComponent(botaocartas)
                    .addComponent(botaopular))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaopararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopararActionPerformed
        Fim f = new Fim();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaopararActionPerformed

    private void label4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label4ActionPerformed

    private void lancarperguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancarperguntaActionPerformed
        Integer idsorteio = (int) (Math.random() * lista.size());
        for (Pergunta p : lista) {
            if (p.getId() == idsorteio) {
                txtEnunciado.setText(p.getEnunciado());
                label1.setText(p.getA());
                label2.setText(p.getB());
                label3.setText(p.getC());
                label4.setText(p.getD());
            } 
        }
    }//GEN-LAST:event_lancarperguntaActionPerformed

    private void label2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label2ActionPerformed

    private void botaocartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocartasActionPerformed
        
    }//GEN-LAST:event_botaocartasActionPerformed

    private void botaoconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoconfirmarActionPerformed
       
    }//GEN-LAST:event_botaoconfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerguntaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerguntaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerguntaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerguntaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerguntaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaocartas;
    private javax.swing.JButton botaoconfirmar;
    private javax.swing.JButton botaoparar;
    private javax.swing.JButton botaopular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton label1;
    private javax.swing.JRadioButton label2;
    private javax.swing.JRadioButton label3;
    private javax.swing.JRadioButton label4;
    private javax.swing.JButton lancarpergunta;
    private javax.swing.JLabel txtEnunciado;
    // End of variables declaration//GEN-END:variables
}
