/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

import javax.swing.JOptionPane;

public class Cartas extends javax.swing.JFrame {

    Integer num;

    /**
     * Creates new form Cartas
     */
    public Cartas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartaslbl = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cartaslbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cartaslbl.setForeground(new java.awt.Color(0, 0, 153));
        cartaslbl.setText("CARTAS");

        ok.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ok.setForeground(new java.awt.Color(255, 0, 0));
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cartaazul.png"))); // NOI18N
        bt1.setBorder(null);
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cartavermelha.png"))); // NOI18N
        bt2.setBorder(null);
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cartaazul.png"))); // NOI18N
        bt3.setBorder(null);
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cartavermelha.png"))); // NOI18N
        bt4.setBorder(null);
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt1)
                        .addGap(18, 18, 18)
                        .addComponent(bt2)
                        .addGap(18, 18, 18)
                        .addComponent(bt3)
                        .addGap(18, 18, 18)
                        .addComponent(bt4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(ok))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(cartaslbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(cartaslbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt1)
                    .addComponent(bt2)
                    .addComponent(bt3)
                    .addComponent(bt4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        //Jogo.setCartas(false);
        Jogo.setH(num);
        this.dispose();
    }//GEN-LAST:event_okActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        int x = 0 + (int) (Math.random() * 3);
        if (x == 0) {
            bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nenhuma.png")));
            JOptionPane.showMessageDialog(rootPane, "Nenhuma!");
            num = 0;
        } else if (x == 1) {
            bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1.png")));
            num = 1;
        } else if (x == 2) {
            bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.png")));
            num = 2;
        } else if (x == 3) {
            bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3a.png")));
            num = 3;
        }

        bt1.setEnabled(false);
        bt2.setEnabled(false);
        bt3.setEnabled(false);
        bt4.setEnabled(false);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        int x = 0 + (int) (Math.random() * 3);
        if (x == 0) {
            bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nenhuma.png")));
            JOptionPane.showMessageDialog(rootPane, "Nenhuma!");
            num = 0;
        } else if (x == 1) {
            bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1.png")));
            num = 1;
        } else if (x == 2) {
            bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.png")));
            num = 2;
        } else if (x == 3) {
            bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3a.png")));
            num = 3;
        }

        bt1.setEnabled(false);
        bt2.setEnabled(false);
        bt3.setEnabled(false);
        bt4.setEnabled(false);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        int x = 0 + (int) (Math.random() * 3);
        if (x == 0) {
            bt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nenhuma.png")));
            JOptionPane.showMessageDialog(rootPane, "Nenhuma!");
            num = 0;
        } else if (x == 1) {
            bt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1.png")));
            num = 1;
        } else if (x == 2) {
            bt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.png")));
            num = 2;
        } else if (x == 3) {
            bt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3a.png")));
            num = 3;
        }

        bt1.setEnabled(false);
        bt2.setEnabled(false);
        bt3.setEnabled(false);
        bt4.setEnabled(false);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        int x = 0 + (int) (Math.random() * 3);
        if (x == 0) {
            bt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nenhuma.png")));
            JOptionPane.showMessageDialog(rootPane, "Nenhuma!");
            num = 0;
        } else if (x == 1) {
            bt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1.png")));
            num = 1;
        } else if (x == 2) {
            bt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.png")));
            num = 2;
        } else if (x == 3) {
            bt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3a.png")));
            num = 3;
        }

        bt1.setEnabled(false);
        bt2.setEnabled(false);
        bt3.setEnabled(false);
        bt4.setEnabled(false);
    }//GEN-LAST:event_bt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JLabel cartaslbl;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
